server:
  port: 5656

security.auth.enabled: false

eventsRateDisplayLimit: 50

kafka:
  topic:
    events: live-events
    strategies: strategies
    alerts: alerts
    latency: latency
    current-strategies: current-strategies
  listeners:
    events.id: events-listener

  bootstrap-servers: localhost:9092

web-socket:
  topic:
    events: /topic/events
    alerts: /topic/alerts
    latency: /topic/latency

management.endpoints.web.exposure.include: mappings, loggers
spring:
  h2.console.enabled: true
  thymeleaf.cache: false
  autoconfigure.exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer